exams/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile", views.profile, name="profile"),
    path("s/<str:andy>", views.takeha, name="andy"),

]

exams_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("exams.urls"))

]

exams/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass


class Question(models.Model):
    text = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.text


class Test(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test_num = models.CharField(max_length=15)
    results = models.IntegerField()

exams/forms.py
from django import forms
from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['text', 'is_correct']

exams/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .forms import QuestionForm, ChoiceForm
from django import forms
from django.utils.datastructures import MultiValueDictKeyError


# Create your views here.
from .models import User, Question, Choice
from django.db import IntegrityError


@login_required(login_url='/login')
def index(request):
    return render(request, "exams/home.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "exams/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "exams/login.html")


def profile(request):
    if request.method == 'POST':
        question_choices = {}
        for question in Question.objects.all():
            choice_id = request.POST.get('question_{}'.format(question.id))
            if choice_id:
                question_choices['question_{}'.format(
                    question.id)] = int(choice_id)
        request.session['question_choices'] = question_choices

    questions = Question.objects.all()
    paginator = Paginator(questions, 1)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "exams/profile.html", {
        "message": "Ich bin du",
        "question": questions,
        "page_obj": page_obj
    })

    # questions = {"question1": "why like this?",
    #              "choice 1": {
    #                  "answer": "ich bin du",
    #                  "isCorrect": True
    #              },
    #              "choice 2": {
    #                  "answer": "Takeha",
    #                  "isCorrect": False
    #              },
    #              "choice 3": {
    #                  "answer": "Sawade ka",
    #                  "isCorrect": False
    #              },
    #              "choice 4": {
    #                  "answer": "Danti",
    #                  "isCorrect": False
    #              },

    #              }

  

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "exams/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "exams/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "exams/register.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def takeha(request, andy):
    return HttpResponse(f"takfeen ya {andy.capitalize()}")

exams/templates/exams/home.html
{% extends 'exams/layout.html' %}
{%block body%}
<h1>Test </h1>
<h2>Test</h2>
<h3 class="andrjaw">Test</h3>
<h3>Test</h3>
{%endblock%}

exams/templates/exams/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>Website</title>
    <link rel="stylesheet" href="{% static 'exams/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Practice Exams</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index'%}">Home</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'profile'%}">Frofile</a>

                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'register'%}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {%else%}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Welcome ya {{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>

                    {%endif%}

                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col">

            </div>
            <div class="col-10">
                {%block body %}

                {% endblock %}
            </div>
            <div class="col">

            </div>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

exams/templates/exams/login.html
{% extends 'exams/layout.html'%}

{% block body %}
<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

Don't have an account? <a href="{% url 'register' %}">Register here.</a>
{% endblock %}

exams/templates/exams/profile.html
{% extends 'exams/layout.html'%}


{%block body%}

<h1>
    Willkommen

</h1>
<h2>{{message}}</h2>
<h2>Hello {{user.username}}</h2>
<h2>Your Id is {{user.id}}</h2>
<h2>Your email is {{user.email}}</h2>

{% for question in page_obj %}
    <form action="{% url 'profile' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>{{ question.text }}</legend>
            {% for choice in question.choice_set.all %}
                <div>
                    <input type="radio" id="choice{{ forloop.counter }}" name="question_{{ question.id }}"
                           value="{{ choice.id }}"
                           {% if request.session.question_choices and request.session.question_choices.question_question.id == choice.id %}
                               checked
                           {% endif %}
                    >
                    <label for="choice{{ forloop.counter }}">{{ forloop.counter }} - {{ choice.text }}</label>
                </div>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Submit">
    </form>
    <br>
{% endfor %}








<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{%endblock%}

exams/templates/exams/register.html
{% extends 'exams/layout.html'%}

{% block body %}

<h1>Register</h1>
{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Already have an account? <a href="{% url 'login' %}">Log In here.</a>
{% endblock %}